### ISSUE TITLE
vscode 繁化姬

https://github.com/Fanhuaji/Sublime-Fanhuaji

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/open-source-ideas#36]
vscode 繁化姬

https://github.com/Fanhuaji/Sublime-Fanhuaji

**Comment by jfcherng** [comment]
FYI, https://github.com/lightyen/vscode-fanhuaji but maybe you want to create your own.

**Comment by Yukaii** [comment]
Nice, I don't want to reinvent the wheel actually 😆
